language: go
go:
  - 1.12
  - tip
before_install:
  - go get github.com/golang/dep/...
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - $GOPATH/bin/dep ensure
script:
  - go test
  - "$HOME/gopath/bin/goveralls -service=travis-ci"
matrix:
  allow_failures:
    - go: tip
branches:
  only:
    - master
