language: go

# You don't need to test on very old version of the Go compiler. It's the user's
# responsibility to keep their compilers up to date.
go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

install:
  - go get -u github.com/golang/lint/golint

# Don't email me the results of the test runs.
notifications:
  email: false

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - go vet ./...
  - go test -v ./... # Run all the tests
