language: go
go:
  - 1.12
  - tip
before_install:
  - go get github.com/golang/dep/...
install:
  - $GOPATH/bin/dep ensure
script:
  - go test
matrix:
  allow_failures:
    - go: tip
branches:
  only:
    - master
# Don't email me the results of the test runs.
notifications:
  email: false
